#!/bin/sh
ssh gvassallo@212.24.98.185 << EOF 
  cd ~/padlock
  git pull 
  npm install
  NODE_ENV='production' webpack --config=webpack-production.config.js 
  NODE_ENV='production' forever restartall
exit 
EOF 
