export const RECEIVE_AUTHED_USER = 'RECEIVE_AUTHED_USER';
export const RECEIVE_ACCESS_TOKEN = 'RECEIVE_ACCESS_TOKEN';
export const RESET_USER_AND_TOKEN = 'RESET_USER_AND_TOKEN'; 
export const LOGIN = 'LOGIN'; 
export const RECEIVE_LOGINS_LIST = 'RECEIVE_LOGINS_LIST'; 
export const RECEIVE_NEW_LOGIN = 'RECEIVE_NEW_LOGIN'; 
export const RECEIVE_USER_INFO = 'RECEIVE_USER_INFO'; 
