export const RECEIVE_AUTHED_USER = 'RECEIVE_AUTHED_USER';
export const RECEIVE_ACCESS_TOKEN = 'RECEIVE_ACCESS_TOKEN';
export const RESET_USER_AND_TOKEN = 'RESET_USER_AND_TOKEN'; 
export const LOGIN = 'LOGIN'; 
export const RECEIVE_SERVICES_LIST = 'RECEIVE_SERVICES_LIST'; 

